In [27]:
import numpy as np
import pandas as pd

In [96]:
df = pd.read_csv('Variables_Municipios.csv')
df

CP     Entidad               Alcaldia  P_NIVSOCEC  Sum_Servicios  \
0    44360     Jalisco  San Pedro Tlaquepaque      121.35            855   
1    44100     Jalisco  San Pedro Tlaquepaque      130.55           1037   
2    44200     Jalisco  San Pedro Tlaquepaque      139.48            932   
3    36700  Guanajuato              Salamanca      114.95            275   
4    44730     Jalisco  San Pedro Tlaquepaque      120.88            471   
..     ...         ...                    ...         ...            ...   
325  36715  Guanajuato              Salamanca      234.61              0   
326  36753  Guanajuato              Salamanca       76.07              0   
327  36850  Guanajuato              Salamanca       54.35             14   
328  36866  Guanajuato              Salamanca       34.69              0   
329  36897  Guanajuato              Salamanca       64.15              1   

     Num_Celulares  Num_Autos  Empresas  Empleos  
0              263         30      6522    26230  
1              347         25      5564    41704  
2              373         48      4803    32203  
3              123        130      3092    12628  
4              229         71      2996    14553  
..             ...        ...       ...      ...  
325              0         58         1        3  
326              0        116         1        3  
327             32         94         1        3  
328              0         21         1        3  
329              0         30         1        3  

[330 rows x 9 columns]

In [94]:
b = a['P_NIVSOCEC'].to_list()
b.sort()
b

[0.0,
 59.89,
 67.0,
 91.87,
 94.87,
 96.74,
 98.14,
 98.88,
 103.01,
 104.81,
 105.45,
 106.1,
 106.1,
 106.8,
 107.11,
 107.64,
 107.73,
 108.33,
 109.09,
 109.33,
 109.58,
 109.82,
 110.46,
 110.62,
 111.19,
 111.47,
 111.59,
 111.73,
 112.35,
 112.94,
 113.19,
 113.19,
 114.43,
 114.44,
 114.58,
 114.6,
 114.6,
 115.08,
 116.16,
 116.19,
 116.83,
 116.97,
 117.12,
 117.37,
 117.58,
 118.04,
 118.64,
 119.02,
 119.58,
 119.76,
 120.02,
 120.1,
 120.24,
 120.25,
 120.47,
 120.88,
 121.35,
 121.71,
 121.74,
 121.91,
 122.07,
 122.28,
 122.28,
 122.28,
 122.73,
 122.77,
 123.07,
 123.67,
 123.74,
 124.78,
 124.83,
 125.24,
 126.17,
 126.56,
 126.8,
 126.86,
 127.35,
 127.51,
 128.64,
 129.07,
 129.83,
 130.21,
 130.55,
 131.17,
 131.35,
 131.6,
 131.81,
 131.82,
 132.88,
 132.88,
 132.88,
 133.0,
 133.4,
 133.85,
 134.37,
 135.85,
 136.81,
 136.81,
 137.02,
 137.36,
 138.43,
 138.6,
 138.64,
 138.93,
 139.0,
 139.18,
 139.48,
 139.52,
 139.63,
 139.65,
 140.28,
 140.76,
 141.04,
 141.8

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   CP                 330 non-null    int64  
 1   Entidad            330 non-null    object 
 2   Alcaldia           330 non-null    object 
 3   P_NIVSOCEC         330 non-null    float64
 4   Sum_Servicios      330 non-null    int64  
 5   Num_Celulares      330 non-null    int64  
 6   Num_Autos          330 non-null    int64  
 7   Empresas           330 non-null    int64  
 8   Empleos            330 non-null    int64  
 9   Cal_P_NIVSOCEC     330 non-null    object 
 10  Cal_Sum_Servicios  330 non-null    object 
dtypes: float64(1), int64(6), object(4)
memory usage: 28.5+ KB


In [47]:
variables = ['P_NIVSOCEC', 'Sum_Servicios']
alcaldia = df.Alcaldia.unique()
quantiles = []

for w in variables:
    nombre = "Cal_"+str(w)
    df[nombre] = ""


for x in alcaldia:   
    for y in variables:
        
        consulta = df[df['Alcaldia'] == str(x)][[str(y)]].reset_index()
        qs = consulta[y].quantile([.2, .4, .6, .8]).values
        quantiles.append(qs)
        nombre = "Cal_"+str(y)
    
        for a,b in consulta.itertuples(index=False):
            if b <= qs[0]:
                df.loc[a, str(nombre)] = "6"
            elif (b <= qs[1]) & (b > qs[0]):
                df.loc[a, str(nombre)] = "7"
            elif (b <= qs[2]) & (b > qs[1]):
                df.loc[a, str(nombre)] = "8"
            elif (b <= qs[3]) & (b > qs[2]):
                df.loc[a, str(nombre)] = "9"
            else:
                df.loc[a, str(nombre)] = "10"
        

In [95]:
alcaldia = df.Alcaldia.unique()
alcaldia

array(['San Pedro Tlaquepaque', 'Salamanca', 'Coacalco de Berrizabal',
       'Cuautlancingo', 'Chicoloapan de Juárez'], dtype=object)

In [48]:
quantiles

[array([116.166, 127.414, 142.742, 179.096]),
 array([  0. ,  18.4,  50.6, 163.4]),
 array([ 58.898,  81.82 , 106.322, 124.35 ]),
 array([ 0. ,  3. ,  9. , 27.6]),
 array([107.24 , 113.438, 122.2  , 131.08 ]),
 array([  0. ,  23.4,  45.2, 165.8]),
 array([ 75.238,  94.56 , 110.96 , 139.542]),
 array([ 7.4, 18. , 36.4, 73. ]),
 array([57.842, 72.38 , 81.794, 98.388]),
 array([  2. ,  48.2,  79.8, 118.8])]

In [51]:
variables = ['P_NIVSOCEC', 'Sum_Servicios']
alcaldia = df.Alcaldia.unique()
quantiles = []

for w in variables:
    nombre = "Cal_"+str(w)
    df[nombre] = ""


for x in alcaldia:   
    for y in variables:
        
        consulta = df[df['Alcaldia'] == str(x)][[str(y)]].reset_index()
        qs = consulta[y].quantile([.2, .4, .6, .8, 1]).values
        quantiles.append(qs)
        nombre = "Cal_"+str(y)
    
        for a,b in consulta.itertuples(index=False):
            if b <= qs[0]:
                df.loc[a, str(nombre)] = "6"
            elif (b <= qs[1]) & (b > qs[0]):
                df.loc[a, str(nombre)] = "7"
            elif (b <= qs[2]) & (b > qs[1]):
                df.loc[a, str(nombre)] = "8"
            elif (b <= qs[3]) & (b > qs[2]):
                df.loc[a, str(nombre)] = "9"
            else:
                df.loc[a, str(nombre)] = "10"
        

In [52]:
quantiles

[array([116.166, 127.414, 142.742, 179.096, 230.1  ]),
 array([   0. ,   18.4,   50.6,  163.4, 1037. ]),
 array([ 58.898,  81.82 , 106.322, 124.35 , 234.61 ]),
 array([  0. ,   3. ,   9. ,  27.6, 287. ]),
 array([107.24 , 113.438, 122.2  , 131.08 , 149.04 ]),
 array([  0. ,  23.4,  45.2, 165.8, 442. ]),
 array([ 75.238,  94.56 , 110.96 , 139.542, 188.7  ]),
 array([  7.4,  18. ,  36.4,  73. , 299. ]),
 array([ 57.842,  72.38 ,  81.794,  98.388, 123.47 ]),
 array([  2. ,  48.2,  79.8, 118.8, 185. ])]