In [137]:
import numpy as np
import pandas as pd

In [150]:
df = pd.read_csv('Precio_Municipios.csv')

# Me quedo con 15 y 19, transpongo estos años, renombro y calculo la plusvalia
precios = df[(df['Year'] == 2015) | (df['Year'] == 2020) ][['Entidad', 'Municipio', 'CP', 'Year', 'Precio_x_m2']]
precios = pd.pivot_table(precios, values = 'Precio_x_m2', columns = 'Year',index=['Entidad','Municipio','CP']).reset_index()
precios.rename(columns = {2015: 'precio_15', 2020: 'precio_20'}, inplace = True)
precios['plus_20/15'] = precios['precio_20'] / precios['precio_15']
precios.head()


variables = ['precio_15', 'precio_20', 'plus_20/15']
alcaldia = precios.Municipio.unique()

for w in variables:
    nombre = "Cal_"+str(w)
    precios[nombre] = ""


for x in alcaldia:   
    for y in variables:
        
        consulta = precios[precios['Municipio'] == str(x)][[str(y)]].reset_index()
        qs = consulta[y].quantile([.2, .4, .6, .8, 1]).values
        
        nombre = "Cal_"+str(y)
    
        for a,b in consulta.itertuples(index=False):
            if b <= qs[0]:
                precios.loc[a, str(nombre)] = "6"
            elif (b <= qs[1]) & (b > qs[0]):
                precios.loc[a, str(nombre)] = "7"
            elif (b <= qs[2]) & (b > qs[1]):
                precios.loc[a, str(nombre)] = "8"
            elif (b <= qs[3]) & (b > qs[2]):
                precios.loc[a, str(nombre)] = "9"
            elif b <= qs[4]:
                precios.loc[a, str(nombre)] = "10"
            else:
                precios.loc[a, str(nombre)] = "5"
                
precios

Year     Entidad      Municipio     CP  precio_15  precio_20  plus_20/15  \
0     Guanajuato      Salamanca  36700    6954.65    9370.61    1.347388   
1     Guanajuato      Salamanca  36710    8375.76   10517.59    1.255718   
2     Guanajuato      Salamanca  36714    5571.65        NaN         NaN   
3     Guanajuato      Salamanca  36715    9976.22        NaN         NaN   
4     Guanajuato      Salamanca  36717   10479.00   13433.10    1.281907   
..           ...            ...    ...        ...        ...         ...   
141       Puebla  Cuautlancingo  72724    8329.33   12946.02    1.554269   
142       Puebla  Cuautlancingo  72725   11195.41        NaN         NaN   
143       Puebla  Cuautlancingo  72730    9835.08   11867.63    1.206663   
144       Puebla  Cuautlancingo  72733    9234.51   11225.56    1.215610   
145       Puebla  Cuautlancingo  72735    9169.73   12692.53    1.384177   

Year Cal_precio_15 Cal_precio_20 Cal_plus_20/15  
0                8             8              9  
1                9             9              7  
2                6             5              5  
3               10             5              5  
4               10            10              8  
..             ...           ...            ...  
141              6             9             10  
142             10             5              5  
143             10             8              6  
144              9             7              7  
145              8             9              9  

[146 rows x 9 columns]

In [189]:
df = pd.read_csv('Precio_Municipios.csv')

In [190]:
df      

Entidad      Municipio     CP  Year  Num_Transacciones  Precio_x_m2
0    Guanajuato      Salamanca  36887  2020                  1      9066.79
1    Guanajuato      Salamanca  36885  2020                 16      9452.25
2    Guanajuato      Salamanca  36883  2020                  1      8543.76
3    Guanajuato      Salamanca  36877  2020                  1     12610.97
4    Guanajuato      Salamanca  36875  2020                  1     11820.10
..          ...            ...    ...   ...                ...          ...
808      Puebla  Cuautlancingo  72705  2015                 29      9368.69
809      Puebla  Cuautlancingo  72704  2015                 10      8473.95
810      Puebla  Cuautlancingo  72703  2015                 18      8334.02
811      Puebla  Cuautlancingo  72702  2015                 22      8604.36
812      Puebla  Cuautlancingo  72700  2015                476      9251.60

[813 rows x 6 columns]

In [193]:
df['CP'].unique

<bound method Series.unique of 0      36887
1      36885
2      36883
3      36877
4      36875
       ...  
808    72705
809    72704
810    72703
811    72702
812    72700
Name: CP, Length: 813, dtype: int64>

In [123]:
df.Year.unique()

array([2020, 2019, 2018, 2017, 2016, 2015], dtype=int64)

In [140]:
# Me quedo con 15 y 19, transpongo estos años, renombro y calculo la plusvalia
precios = df[(df['Year'] == 2015) | (df['Year'] == 2020) ][['Entidad', 'Municipio', 'CP', 'Year', 'Precio_x_m2']]
precios = pd.pivot_table(precios, values = 'Precio_x_m2', columns = 'Year',index=['Entidad','Municipio','CP']).reset_index()
precios.rename(columns = {2015: 'precio_15', 2020: 'precio_20'}, inplace = True)
precios['plus_20/15'] = precios['precio_20'] / precios['precio_15']
precios.head()

Year     Entidad  Municipio     CP  precio_15  precio_20  plus_20/15
0     Guanajuato  Salamanca  36700    6954.65    9370.61    1.347388
1     Guanajuato  Salamanca  36710    8375.76   10517.59    1.255718
2     Guanajuato  Salamanca  36714    5571.65        NaN         NaN
3     Guanajuato  Salamanca  36715    9976.22        NaN         NaN
4     Guanajuato  Salamanca  36717   10479.00   13433.10    1.281907

In [ ]:
# Parece que la funcion deja aparte a los nulos

In [141]:
precios[(precios['precio_15'].notnull())  & (precios['Municipio']== 'Salamanca')]['precio_15'].quantile([.2, .4, .6, .8]).values

array([5986.01, 6456.37, 7521.51, 8375.76])

In [142]:
consulta = precios[precios['Municipio'] == 'Salamanca'][['precio_15']].reset_index()
qs = consulta[consulta['precio_15'].notnull()]['precio_15'].quantile([.2, .4, .6, .8]).values
qs

array([5986.01, 6456.37, 7521.51, 8375.76])

In [149]:
consulta = precios[precios['Municipio'] == 'Salamanca'][['precio_15']].reset_index()
qs = consulta['precio_15'].quantile([.2, .4, .6, .8]).values
qs

array([5986.01, 6456.37, 7521.51, 8375.76])

In [160]:
variables = ['precio_15', 'precio_20', 'plus_20/15']
alcaldia = precios.Municipio.unique()

for w in variables:
    nombre = "Cal_"+str(w)
    precios[nombre] = ""
    
min15 =  precios['precio_15'].min()
min16 =  precios['precio_20'].min()
minpl =  precios['plus_20/15'].min()

precios['precio_15'] = precios['precio_15'].fillna(min15) 
precios['precio_20'] = precios['precio_20'].fillna(min16)
precios['plus_20/15'] = precios['plus_20/15'].fillna(minpl)


for x in alcaldia:   
    for y in variables:
        
        consulta = precios[precios['Municipio'] == str(x)][[str(y)]].reset_index()
        qs = consulta[y].quantile([.2, .4, .6, .8, 1]).values
        
        nombre = "Cal_"+str(y)
    
        for a,b in consulta.itertuples(index=False):
            if b <= qs[0]:
                precios.loc[a, str(nombre)] = "6"
            elif (b <= qs[1]) & (b > qs[0]):
                precios.loc[a, str(nombre)] = "7"
            elif (b <= qs[2]) & (b > qs[1]):
                precios.loc[a, str(nombre)] = "8"
            elif (b <= qs[3]) & (b > qs[2]):
                precios.loc[a, str(nombre)] = "9"
            elif b <= qs[4]:
                precios.loc[a, str(nombre)] = "10"
            else:
                precios.loc[a, str(nombre)] = "5"
precios

Year     Entidad      Municipio     CP  precio_15  precio_20  plus_20/15  \
0     Guanajuato      Salamanca  36700    6954.65    9370.61    1.347388   
1     Guanajuato      Salamanca  36710    8375.76   10517.59    1.255718   
2     Guanajuato      Salamanca  36714    5571.65    5346.28    0.623941   
3     Guanajuato      Salamanca  36715    9976.22    5346.28    0.623941   
4     Guanajuato      Salamanca  36717   10479.00   13433.10    1.281907   
..           ...            ...    ...        ...        ...         ...   
141       Puebla  Cuautlancingo  72724    8329.33   12946.02    1.554269   
142       Puebla  Cuautlancingo  72725   11195.41    5346.28    0.623941   
143       Puebla  Cuautlancingo  72730    9835.08   11867.63    1.206663   
144       Puebla  Cuautlancingo  72733    9234.51   11225.56    1.215610   
145       Puebla  Cuautlancingo  72735    9169.73   12692.53    1.384177   

Year Cal_precio_15 Cal_precio_20 Cal_plus_20/15  
0                8             9              9  
1               10             9              8  
2                7             6              6  
3               10             6              6  
4               10            10              9  
..             ...           ...            ...  
141              6            10             10  
142             10             6              6  
143             10             8              7  
144              9             7              7  
145              8             9             10  

[146 rows x 9 columns]

In [155]:
variables = ['precio_15', 'precio_20', 'plus_20/15']
alcaldia = precios.Municipio.unique()

for w in variables:
    nombre = "Cal_"+str(w)
    precios[nombre] = ""


for x in alcaldia:   
    for y in variables:
        
        consulta = precios[precios['Municipio'] == str(x)][[str(y)]].reset_index()    
        qs = consulta[consulta[y].notnull()][y] .quantile([.2, .4, .6, .8]).values
        
        nombre = "Cal_"+str(y)
    
        for a,b in consulta.itertuples(index=False):
            if b <= qs[0]:
                precios.loc[a, str(nombre)] = "6"
            elif (b <= qs[1]) & (b > qs[0]):
                precios.loc[a, str(nombre)] = "7"
            elif (b <= qs[2]) & (b > qs[1]):
                precios.loc[a, str(nombre)] = "8"
            elif (b <= qs[3]) & (b > qs[2]):
                precios.loc[a, str(nombre)] = "9"
            else:
                precios.loc[a, str(nombre)] = "10"
    
precios

Year     Entidad      Municipio     CP  precio_15  precio_20  plus_20/15  \
0     Guanajuato      Salamanca  36700    6954.65    9370.61    1.347388   
1     Guanajuato      Salamanca  36710    8375.76   10517.59    1.255718   
2     Guanajuato      Salamanca  36714    5571.65        NaN         NaN   
3     Guanajuato      Salamanca  36715    9976.22        NaN         NaN   
4     Guanajuato      Salamanca  36717   10479.00   13433.10    1.281907   
..           ...            ...    ...        ...        ...         ...   
141       Puebla  Cuautlancingo  72724    8329.33   12946.02    1.554269   
142       Puebla  Cuautlancingo  72725   11195.41        NaN         NaN   
143       Puebla  Cuautlancingo  72730    9835.08   11867.63    1.206663   
144       Puebla  Cuautlancingo  72733    9234.51   11225.56    1.215610   
145       Puebla  Cuautlancingo  72735    9169.73   12692.53    1.384177   

Year Cal_precio_15 Cal_precio_20 Cal_plus_20/15  
0                8             8              9  
1                9             9              7  
2                6            10             10  
3               10            10             10  
4               10            10              8  
..             ...           ...            ...  
141              6             9             10  
142             10            10             10  
143             10             8              6  
144              9             7              7  
145              8             9              9  

[146 rows x 9 columns]

In [58]:
transacciones = df[(df['Year'] == 2015) | (df['Year'] == 2016) | (df['Year'] == 2017) | (df['Year'] == 2018) | (df['Year'] == 2019)][['Entidad', 'Municipio', 'CP', 'Year', 'Num_Transacciones']]
transacciones = pd.pivot_table(transacciones, values = 'Num_Transacciones', columns = 'Year',index=['Entidad','Municipio','CP']).reset_index()
transacciones.rename(columns = {2015: 'tran_15', 2016: 'tran_16', 2017: 'tran_17', 2018: 'tran_18', 2019: 'tran_19'}, inplace = True)
transacciones.head()

Year     Entidad  Municipio     CP  tran_15  tran_16  tran_17  tran_18  \
0     Guanajuato  Salamanca  36700     13.0     28.0     29.0     18.0   
1     Guanajuato  Salamanca  36704      NaN      NaN      NaN      NaN   
2     Guanajuato  Salamanca  36710    161.0     39.0    122.0      6.0   
3     Guanajuato  Salamanca  36714      2.0      5.0      2.0      1.0   
4     Guanajuato  Salamanca  36715      1.0      NaN      1.0      NaN   

Year  tran_19  
0        23.0  
1         1.0  
2         NaN  
3         2.0  
4         NaN

In [162]:
variables = ['tran_15', 'tran_16', 'tran_17', 'tran_18', 'tran_19']
alcaldia = transacciones.Municipio.unique()

for w in variables:
    nombre = "Cal_"+str(w)
    transacciones[nombre] = ""


for x in alcaldia:   
    for y in variables:
        
        consulta = transacciones[transacciones['Municipio'] == str(x)][[str(y)]].reset_index()
        qs = consulta[y].quantile([.2, .4, .6, .8, 1]).values
        
        nombre = "Cal_"+str(y)
    
        for a,b in consulta.itertuples(index=False):
            if b <= qs[0]:
                transacciones.loc[a, str(nombre)] = "6"
            elif (b <= qs[1]) & (b > qs[0]):
                transacciones.loc[a, str(nombre)] = "7"
            elif (b <= qs[2]) & (b > qs[1]):
                transacciones.loc[a, str(nombre)] = "8"
            elif (b <= qs[3]) & (b > qs[2]):
                transacciones.loc[a, str(nombre)] = "9"
            elif b <= qs[4]:
                transacciones.loc[a, str(nombre)] = "10"
            else:
                transacciones.loc[a, str(nombre)] = "5"
transacciones

Year     Entidad      Municipio     CP  tran_15  tran_16  tran_17  tran_18  \
0     Guanajuato      Salamanca  36700     13.0     28.0     29.0     18.0   
1     Guanajuato      Salamanca  36704      NaN      NaN      NaN      NaN   
2     Guanajuato      Salamanca  36710    161.0     39.0    122.0      6.0   
3     Guanajuato      Salamanca  36714      2.0      5.0      2.0      1.0   
4     Guanajuato      Salamanca  36715      1.0      NaN      1.0      NaN   
..           ...            ...    ...      ...      ...      ...      ...   
156       Puebla  Cuautlancingo  72724     18.0     24.0     16.0     44.0   
157       Puebla  Cuautlancingo  72725      6.0      5.0      3.0      NaN   
158       Puebla  Cuautlancingo  72730    760.0   1016.0   1047.0    170.0   
159       Puebla  Cuautlancingo  72733     33.0      9.0     15.0      7.0   
160       Puebla  Cuautlancingo  72735     44.0     55.0     50.0     29.0   

Year  tran_19 Cal_tran_15 Cal_tran_16 Cal_tran_17 Cal_tran_18 Cal_tran_19  
0        23.0           8           9           9           9           9  
1         1.0           5           5           5           5           6  
2         NaN          10          10          10           8           5  
3         2.0           6           7           6           6           7  
4         NaN           6           5           6           5           5  
..        ...         ...         ...         ...         ...         ...  
156     145.0           7           7           7           9          10  
157       3.0           7           6           6           5           6  
158      70.0          10          10          10          10           9  
159       8.0           9           7           7           6           7  
160      51.0           9           9           8           8           9  

[161 rows x 13 columns]

In [186]:
# Cambio de transacciones
cambio = df[(df['Year'] == 2016) | (df['Year'] == 2017) | (df['Year'] == 2019)][['Entidad', 'Municipio', 'CP', 'Year', 'Num_Transacciones']]

In [187]:
cambio = pd.pivot_table(cambio, values = 'Num_Transacciones', columns = 'Year',index=['Entidad','Municipio','CP']).reset_index()
cambio['2016-2019'] = cambio[2019] - cambio[2016]
cambio['2017-2019'] = cambio[2019] - cambio[2017]
cambio = cambio[['Entidad', 'Municipio', 'CP', '2016-2019', '2017-2019']]
cambio.head()

Year     Entidad  Municipio     CP  2016-2019  2017-2019
0     Guanajuato  Salamanca  36700       -5.0       -6.0
1     Guanajuato  Salamanca  36704        NaN        NaN
2     Guanajuato  Salamanca  36710        NaN        NaN
3     Guanajuato  Salamanca  36714       -3.0        0.0
4     Guanajuato  Salamanca  36715        NaN        NaN

In [188]:
variables = ['2016-2019', '2017-2019']
alcaldia = cambio.Municipio.unique()

for w in variables:
    nombre = "Cal_"+str(w)
    cambio[nombre] = ""


for x in alcaldia:   
    for y in variables:
        
        consulta = cambio[cambio['Municipio'] == str(x)][[str(y)]].reset_index()
        qs = consulta[y].quantile([.2, .4, .6, .8, 1]).values
        
        nombre = "Cal_"+str(y)
    
        for a,b in consulta.itertuples(index=False):
            if b <= qs[0]:
                cambio.loc[a, str(nombre)] = "6"
            elif (b <= qs[1]) & (b > qs[0]):
                cambio.loc[a, str(nombre)] = "7"
            elif (b <= qs[2]) & (b > qs[1]):
                cambio.loc[a, str(nombre)] = "8"
            elif (b <= qs[3]) & (b > qs[2]):
                cambio.loc[a, str(nombre)] = "9"
            elif b <= qs[4]:
                cambio.loc[a, str(nombre)] = "10"
            else:
                cambio.loc[a, str(nombre)] = "5"
cambio

Year     Entidad      Municipio     CP  2016-2019  2017-2019 Cal_2016-2019  \
0     Guanajuato      Salamanca  36700       -5.0       -6.0             6   
1     Guanajuato      Salamanca  36704        NaN        NaN             5   
2     Guanajuato      Salamanca  36710        NaN        NaN             5   
3     Guanajuato      Salamanca  36714       -3.0        0.0             7   
4     Guanajuato      Salamanca  36715        NaN        NaN             5   
..           ...            ...    ...        ...        ...           ...   
154       Puebla  Cuautlancingo  72724      121.0      129.0            10   
155       Puebla  Cuautlancingo  72725       -2.0        0.0             8   
156       Puebla  Cuautlancingo  72730     -946.0     -977.0             6   
157       Puebla  Cuautlancingo  72733       -1.0       -7.0             8   
158       Puebla  Cuautlancingo  72735       -4.0        1.0             7   

Year Cal_2017-2019  
0                7  
1                5  
2                5  
3                8  
4                5  
..             ...  
154             10  
155              9  
156              6  
157              8  
158              9  

[159 rows x 7 columns]